name: test

on: [pull_request]

jobs:
  release:
    name: Deploy product to OBS and refresh CDN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Environment 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Build
      run: |
        pip install -r requirements.txt
        mkdocs build --strict --verbose

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pull-request-artifact
        path: |
          public

